services:
  webmin-bind:
    image: kcancook/webmin-bind:latest
    container_name: webmin-bind
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:10000/tcp"
    environment:
      TZ: America/New_York
      ROOT_PASSWORD: change-me-now
    volumes:
      - ./data/etc-bind:/etc/bind
      - ./data/cache-bind:/var/cache/bind
      - ./data/lib-bind:/var/lib/bind
